<div class="row col-12">

<?php foreach ($this->modules as $u) :?>
<?php if(in_array($u['id'],$this->user['module'])):?>
<div class="col-3">
    <a class="text-dark" href="<?php echo $u['path'];?>" target="_self">
        <div class="card bg-dark">
            <div class="card card-header bg-dark tx-white">
            <h5><?php echo $u['module'];?></h5>
            </div>
            <div class="card card-body text-center height-180">
                <p><?php echo $u['description'];?></p>
                <span class="fa-2x"> 
                    <i class="<?php echo $u['img'];?> fa-3x"></i>
                </span>
            </div>
        </div>
    </a>
</div>
<?php endif; ?>
<?php endforeach; ?>


</div>

